### ISSUE TITLE
launches

### ISSUE THREAD

**Issue by peachwadsprite** [zolantris/ValheimMods#123]
### What happened?

it didnt work this way at first but recently after game update, my ship will launch me straight to the branches of the world tree. i noticed the speed configs and turned both down with sail speed not exceeding propulsion speed. still i get launched. is this a bug or perhaps a result of dropping anchor in not as deep waters? (the hull is not at all touching the sea floor)

### Steps to reproduce

1. load game and world
2. board ship and walk around like normal
3. get launched suddenly

### Log outputs

```txt
sorry, no crash so no logs.
```

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: Major.Minor.Patch
```

**Comment by zolantris** [comment]
Try downgrading to a lower version. Unfortunately pretty busy these next couple days.

Likely only an issue with ramps. (from this mod) turning off experimentaljitterfix should fix it too...but downgrading to 2.2.2 should be enough

**Comment by zolantris** [comment]
Need to update the template. What version  of raft were you on? Guessing 2.2.3.

Also need to know if this was singleplayer or client server or dedicated server.

**Comment by 7R4N** [comment]
I've got the same issue, seems to be happening when I'm close to shore. I've tried downgrading to 2.2.2 and disabled experimentaljitterfix, but the issue persists. I'm on singleplayer.

**Comment by zolantris** [comment]
Not applicable now.
